# Generated by Django 2.2.6 on 2019-11-03 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='edit_date',
            new_name='pub_date',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='pun_date',
        ),
    ]
